export const CATEGORIES_ACTION_TYPES = {
    FETCH_CATEGORIES_REGUEST: 'FETCH_CATEGORIES_REGUEST',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAIL: 'FETCH_CATEGORIES_FAIL'
};